import type { Metadata } from 'next'
import { CodeBlock } from '@/components/CodeBlock'
import { Callout } from '@/components/Callout'
import { FAQ } from '@/components/FAQ'
import { RelatedDocs } from '@/components/RelatedDocs'

export const metadata: Metadata = {
  title: 'How Consent Flow Works — Backend Guide — Consenti',
  description:
    'Trace a consent record from HTTP POST through validation and storage to GDPR erasure.',
  alternates: { canonical: '/guides/backend/consent-flow' },
  openGraph: {
    title: 'How Consent Flow Works — Backend Guide — Consenti',
    description:
      'Trace a consent record from HTTP POST through validation and storage to GDPR erasure.',
    url: 'https://consenti.dev/guides/backend/consent-flow',
    siteName: 'Consenti Docs',
    images: ['/og-image.jpg'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'How Consent Flow Works — Backend Guide — Consenti',
    description:
      'Trace a consent record from HTTP POST through validation and storage to GDPR erasure.',
    images: ['/og-image.jpg'],
  },
}

export default function BackendConsentFlowGuide() {
  return (
    <div className="prose max-w-none">
      <h1>How Consent Flow Works</h1>
      <p className="lead">
        The backend&apos;s job is to receive consent decisions from the widget, store them durably,
        and provide endpoints for verification and GDPR erasure. This guide traces the full
        lifecycle of a consent record — from the first HTTP POST to deletion.
      </p>

      <h2>The lifecycle at a glance</h2>
      <div className="not-prose my-6 p-5 rounded-xl bg-slate-50 dark:bg-gray-800 border border-slate-200 dark:border-gray-700 font-mono text-sm text-slate-700 dark:text-gray-300 leading-loose">
        <p className="m-0">
          1. Widget submits → <code>POST /consenti/api/v1/consent</code>
          <br />
          2. Route validates input → calls ConsentService
          <br />
          3. Service creates/updates visitor record
          <br />
          4. Service writes consent record to storage
          <br />
          5. EventBus fires <code>consent.created</code>
          <br />
          6. Response 201 → widget writes browser cookie
          <br />
          7. Subsequent loads → <code>GET /consent/:visitorId/verify</code> (optional)
          <br />
          8. GDPR erasure → <code>DELETE /consent/:visitorId</code>
        </p>
      </div>

      <h2>Stage 1 — Widget submits consent</h2>
      <p>
        After the visitor interacts with the banner, the widget sends a POST request if{' '}
        <code>api.enabled: true</code>:
      </p>

      <CodeBlock
        lang="bash"
        code={`POST /consenti/api/v1/consent
Content-Type: application/json

{
  "profileId": "my-profile-id",
  "consentJson": {
    "necessary": "granted",
    "analytics": "granted",
    "marketing": "denied"
  },
  "visitorId": "a1b2c3d4-...",
  "locale": "en",
  "gpcDetected": false,
  "source": "banner"
}`}
      />

      <p>
        The <code>visitorId</code> is a UUID generated by <code>crypto.randomUUID()</code> on the
        widget&apos;s first load and stored in <code>localStorage</code>. It persists across
        sessions in the same browser. If you pass <code>core.userId</code> (for authenticated
        users), the widget uses that as the visitor identifier instead — enabling cross-device sync.
      </p>

      <h2>Stage 2 — Validation</h2>
      <p>
        The route layer validates the request body. Missing required fields or invalid{' '}
        <code>consentJson</code> values return <code>422 Unprocessable Entity</code> with a
        structured error:
      </p>

      <CodeBlock
        lang="json"
        code={`{ "error": "validation_error", "details": ["consentJson.analytics must be 'granted' | 'denied' | 'objected'"] }`}
      />

      <p>
        The route then calls <code>ConsentService.submit()</code>. Services contain all business
        logic — routes never touch storage directly.
      </p>

      <h2>Stage 3 — Visitor upsert</h2>
      <p>
        If this is the first consent from a <code>visitorId</code>, the service creates a new
        visitor record. If the visitor already exists, it updates the record. IP addresses are never
        stored raw — only a SHA-256 hash is persisted:
      </p>

      <CodeBlock
        lang="typescript"
        code={`// Inside the service — you never write this yourself
createHash('sha256').update(req.ip).digest('hex')`}
      />

      <h2>Stage 4 — Consent record written</h2>
      <p>
        The service writes a consent record to the storage adapter. Every update creates a new
        history entry — the full consent change log is always preserved.
      </p>

      <p>Successful response:</p>
      <CodeBlock
        lang="json"
        code={`{
  "id": "record-uuid",
  "visitorId": "visitor-uuid",
  "profileId": "my-profile-id",
  "locale": "en",
  "consentJson": { "necessary": "granted", "analytics": "granted", "marketing": "denied" },
  "gpcDetected": false,
  "source": "banner",
  "createdAt": "2026-07-07T10:00:00.000Z",
  "updatedAt": "2026-07-07T10:00:00.000Z"
}`}
      />

      <h2>Stage 5 — EventBus fires</h2>
      <p>
        After the record is saved, <code>createConsenti()</code> emits events on its{' '}
        <code>eventBus</code>. Subscribe to these to trigger webhooks, forward data to analytics
        platforms, or invalidate CDN caches:
      </p>

      <CodeBlock
        lang="typescript"
        code={`const { eventBus } = createConsenti({ /* ... */ })

eventBus.on('consent.created', (record) => {
  // record: full ConsentDbRecord
  myAnalyticsClient.track('consent_submitted', {
    visitorId: record.visitorId,
    profileId: record.profileId,
    consent: record.consentJson,
  })
})

eventBus.on('consent.updated', ({ previous, current }) => {
  // compare previous and current consent states
})`}
      />

      <Callout type="tip">
        You can also use the <code>afterConsentSave</code> plugin hook to intercept consent saves
        without coupling to the eventBus directly. See the <a href="/docs/api/plugins/">Plugins</a>{' '}
        reference.
      </Callout>

      <h2>Stage 6 — Verify consent (optional)</h2>
      <p>
        On subsequent page loads, the widget can verify the stored cookie against the backend to
        detect a profile change (edits mint a new profile <code>id</code>, so this is how staleness
        is detected — there is no separate version counter) or expired consent:
      </p>

      <CodeBlock
        lang="bash"
        code={`GET /consenti/api/v1/consent/visitor-uuid/verify

# Valid
{ "valid": true, "reasons": [] }

# Stale — profile was edited since the visitor last consented (a new id is now active)
{ "valid": false, "reasons": ["profile_changed"], "currentProfileId": "...", "consentProfileId": "..." }

# Other reasons: "consent_expired" | "hmac_invalid"`}
      />

      <p>
        When verification fails, the widget re-shows the banner automatically (if configured to do
        so).
      </p>

      <h2>Stage 7 — GDPR right to erasure</h2>
      <p>
        GDPR Article 17 gives visitors the right to have their data deleted. Consenti exposes a
        public endpoint for this:
      </p>

      <CodeBlock lang="bash" code={`DELETE /consenti/api/v1/consent/visitor-uuid`} />

      <p>
        This deletes the visitor record, all consent records, and all consent history for that
        visitor. The operation fires a <code>consent.erased</code> event on the eventBus:
      </p>

      <CodeBlock
        lang="typescript"
        code={`eventBus.on('consent.erased', ({ visitorId }) => {
  // Remove from your own DMP / analytics / CRM
  myDmpClient.deleteUser(visitorId)
})`}
      />

      <Callout type="danger">
        The <code>audit_logs</code> table is append-only by design — erasure requests are logged
        there and those log entries are retained for compliance evidence. Only the consent data
        itself is deleted.
      </Callout>

      <RelatedDocs
        items={[
          {
            href: '/docs/api/routes/public/',
            label: 'Public Routes',
            desc: 'Full reference for consent submission, verify, and erasure endpoints',
          },
          {
            href: '/docs/api/events/',
            label: 'Events',
            desc: 'Every eventBus event — consent.created, consent.updated, consent.erased',
          },
          {
            href: '/docs/api/routes/admin/',
            label: 'Admin Routes',
            desc: 'Consent history and other RBAC-protected endpoints',
          },
        ]}
      />

      <h2>Frequently asked questions</h2>
      <FAQ
        items={[
          {
            question: 'Is consent stored per visitor or per browser session?',
            answer: (
              <p className="m-0">
                Per visitor. The <code>visitorId</code> is generated once and stored in{' '}
                <code>localStorage</code>, so it persists across browser sessions on the same
                device. For authenticated users, pass <code>core.userId</code> to the widget — this
                replaces the generated ID with your user&apos;s ID, enabling cross-device sync.
              </p>
            ),
          },
          {
            question: 'What triggers a re-consent?',
            answer: (
              <>
                <ul className="m-0 pl-4 space-y-1">
                  <li>
                    The consent cookie expires (lifetime = the profile&apos;s{' '}
                    <code>expiryDays</code>).
                  </li>
                  <li>
                    The profile is edited (a new profile <code>id</code> becomes active) and
                    verification returns <code>profile_changed</code>.
                  </li>
                  <li>
                    The visitor calls <code>widget.reConsent()</code> or uses a &ldquo;reset
                    preferences&rdquo; link.
                  </li>
                  <li>
                    The backend receives a <code>DELETE /consent/:visitorId</code> request.
                  </li>
                </ul>
              </>
            ),
          },
          {
            question: 'How do I hook into consent saves without modifying the backend code?',
            answer: (
              <p className="m-0">
                Use the <code>eventBus</code> returned by <code>createConsenti()</code> — subscribe
                to <code>consent.created</code> and <code>consent.updated</code>. Alternatively,
                write a plugin that implements <code>afterConsentSave(record)</code> — the plugin is
                called after every save automatically.
              </p>
            ),
          },
          {
            question: 'Can visitors see their consent history?',
            answer: (
              <p className="m-0">
                The admin dashboard shows full consent history per visitor under Consents → select
                visitor → History. Via API:{' '}
                <code>GET /consenti/admin/consents/:visitorId/history</code> (requires admin JWT).
                There is no public endpoint for visitors to self-serve their own history — you would
                need to build that using the admin API from your own server-side code.
              </p>
            ),
          },
        ]}
      />
    </div>
  )
}
