import * as sass from 'sass'
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const input = resolve(__dirname, '../src/styles/index.scss')
const outDir = resolve(__dirname, '../dist')
const output = resolve(outDir, 'index.css')

mkdirSync(outDir, { recursive: true })

const result = sass.compile(input, { style: 'compressed', sourceMap: false })
writeFileSync(output, result.css, 'utf8')
writeFileSync(resolve(outDir, 'style.d.ts'), '// CSS side-effect import — no exports\nexport {}\n', 'utf8')

// Write the CSS as an inline TS string for runtime injection (used by disableCssTemplate: false).
const escaped = result.css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
writeFileSync(
  resolve(__dirname, '../src/styles/consenti-css.ts'),
  `// Auto-generated by scripts/build-css.mjs — do not edit manually.\n// Run \`npm run build --workspace=apps/ui\` to regenerate.\nexport const CONSENTI_CSS = \`${escaped}\`\n`,
  'utf8',
)

console.log(`Built ${output} (${result.css.length} bytes)`)
